{% set name = "blosc" %}
{% set version = "1.10.4" %}
{% set sha256 = "562e617eac025f4247fe5b18cfa7177672c796f4ceaafb35672f917cf6c9a937" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: 
    - export DISABLE_BLOSC_SSE2=1  # [ppc64le]
    - export DISABLE_BLOSC_AVX2=1  # [ppc64le]
    - {{ PYTHON }} -m pip install . -vv
  ignore_run_exports:
    - python
    - blosc

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - blosc
    - pip
    - python >=3.7
    - setuptools
    - scikit-build
    - wheel
  run:
    - blosc
    - numpy
    - python

test:
  imports:
    - blosc
  requires:
    - numpy
    - psutil
  commands:
    - python -c "import blosc; blosc.print_versions()"
    - python -c "import blosc; blosc.test()"

about:
  home: http://python-blosc.blosc.org/
  license_family: BSD
  license: BSD-3-Clause
  summary: A Python wrapper for the extremely fast Blosc compression library
  dev_url: https://github.com/Blosc/python-blosc
  doc_url: http://python-blosc.blosc.org/

extra:
  recipe-maintainers:
    - danielfrg
    - FrancescElies
    - msarahan
