{% set name = "blosc" %}
{% set version = "1.11.4" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e0b312d9554d3aea93c75af4ad70dfa8b815ef4fe2b658c313b2f27ed0f41d37

build:
  number: 0
  skip: true  # [py<310]
  script:
    - export USE_SYSTEM_BLOSC=1  # [unix]
    - set USE_SYSTEM_BLOSC=1  # [win]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.14.0
    - make  # [unix]
    - ninja-base
  host:
    - pip
    - python
    - blosc
    - setuptools
    - scikit-build >=0.11.1
    - py-cpuinfo
  run:
    - python
    - blosc
    - numpy >=1.16

test:
  imports:
    - blosc
  requires:
    - pip
    - psutil
  commands:
    - pip check
    - python -m blosc.test

about:
  home: https://blosc.org/python-blosc
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A Python wrapper for the extremely fast Blosc compression library
  description: |
    Blosc is a high performance compressor optimized for binary data.
    It has been designed to transmit data to the processor cache faster
    than the traditional, non-compressed, direct memory fetch approach via a memcpy() OS call.
  dev_url: https://github.com/Blosc/python-blosc
  doc_url: https://blosc.org/python-blosc

extra:
  recipe-maintainers:
    - danielfrg
    - FrancescElies
    - msarahan
