{% set name = "blosc" %}
{% set version = "1.9.2" %}
{% set sha256 = "89196a2112035836f027a29835ee247b0c7a45cece4cd9e4b740a1428aa174bf" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{PYTHON}} setup.py install --blosc=$PREFIX --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - blosc
  run:
    - python
    - numpy

test:
  imports:
    - blosc
  commands:
    - python -c "import blosc; blosc.print_versions()"
    - python -c "import blosc; blosc.test()"

about:
  home: https://github.com/Blosc/python-blosc
  license_family: Apache
  license: Apache 2.0
  license_file: LICENSES/PYTHON-BLOSC.txt
  summary: 'A Python wrapper for the extremely fast Blosc compression library'

extra:
  recipe-maintainers:
    - danielfrg
    - FrancescElies
    - msarahan
