travis:
  secure:
    BINSTAR_TOKEN: WtltqSaz1QvWj2INS+4fHBWmh/DHjKug+WvqbIzPAsjVsJYlhflEcoWdT5KTDJb+C+xrUwuHtmD+w9C6zpIrPtLXhDs1Ufbd68t42v3dG4l4PghWIzHN2NZ6bCv+YMi1WEE0kEA2aj+vrI96mauPu7iS1vLqvK5ZuR/3T3QPdAmMhKQMAnlfveqpOgPsn7L2twH7B9pw3MK+8qm2QoznejLxlW1lCI/y/4Qi2Ps6t4Kv2sYdqZ2GIMBTYp5dBXKFlPJF5+Uluj0fimz9VwNQFE3Ce0nd87pLOH/YXzn6+QEvc6WaGgrVdV2/g0DDSGGJWzmZEfGPAz44dkR4uocQT9kL0DdBVoWrqucj7lzhSazaaGMfKUX7WCZdGAur34P5TuZSI8ql3Xi0EEN9jTT0sMFuwUCiovSlPyJUbZss0v6idDOdtImmZrFreU21bh2auNg3lS2rWBwmKk09FKiKekeAWmy5sSa5bz53Ti3yY+uARP57KZCK/52ZyxNTFvys7mlIKNTiC6h3UCOZs5G9/2w/3NDViZhemPAFzDKO5aHDk/nmoZ2ofXF+hHvboPmfU1fHy2Q/KZ01VqLV18S2wkJuLM9yQw/1KJnB2h0FpSL41BTgb2yh+4Vd1kiFYmpv26V3PXLzIZhbXZztwqUbvKJU5UqrTfGMWlDNQ2Fn/yA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
